/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionApplication {
  'id' : number,
  'status' : ApplicationStatus,
  'applicantName' : string,
  'institutionName' : string,
  'dateOfBirth' : string,
  'annualIncome' : string,
  'submittedAt' : Time,
  'photoUrl' : string,
  'reviewNote' : string,
  'applicantMobile' : string,
  'reviewedAt' : [] | [Time],
  'district' : string,
  'state' : string,
  'fatherName' : string,
  'address' : string,
  'incomeCertUrl' : string,
  'category' : string,
  'pinCode' : string,
  'classYear' : string,
  'casteCertUrl' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface FeesStructure {
  'id' : number,
  'period' : string,
  'messFeesPerMonth' : bigint,
  'notes' : string,
  'category' : string,
}
export interface GalleryImage {
  'id' : number,
  'title' : string,
  'imageUrl' : string,
  'uploadedAt' : Time,
  'uploadedBy' : string,
}
export interface SiteSettings {
  'announcementText' : string,
  'admissionLink' : string,
  'scholarshipLink' : string,
  'seatsAvailable' : string,
  'studentsEnrolled' : string,
  'yearsOfService' : string,
  'scholarshipsFacilitated' : string,
}
export interface StaffMember {
  'id' : number,
  'bio' : string,
  'order' : bigint,
  'name' : string,
  'designation' : string,
  'role' : string,
  'photoUrl' : string,
  'email' : string,
  'phone' : string,
}
export interface Student {
  'id' : number,
  'admissionDate' : string,
  'name' : string,
  'year' : string,
  'fatherName' : string,
  'rollNumber' : string,
  'category' : string,
  'classLevel' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateFees' : ActorMethod<[FeesStructure], undefined>,
  'addOrUpdateGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addOrUpdateStaff' : ActorMethod<[StaffMember], undefined>,
  'addOrUpdateStudent' : ActorMethod<[Student], undefined>,
  'approveApplication' : ActorMethod<[number, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddStudents' : ActorMethod<[Array<Student>], undefined>,
  'getAllApplications' : ActorMethod<[], Array<AdmissionApplication>>,
  'getAllFees' : ActorMethod<[], Array<FeesStructure>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllStaff' : ActorMethod<[], Array<StaffMember>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFees' : ActorMethod<[number], FeesStructure>,
  'getGalleryImage' : ActorMethod<[number], GalleryImage>,
  'getMyApplication' : ActorMethod<[string], AdmissionApplication>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStaffMember' : ActorMethod<[number], StaffMember>,
  'getStudent' : ActorMethod<[number], Student>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginApplicant' : ActorMethod<[string, string], undefined>,
  'registerApplicant' : ActorMethod<[string, string, string], undefined>,
  'rejectApplication' : ActorMethod<[number, string], undefined>,
  'removeFees' : ActorMethod<[number], undefined>,
  'removeGalleryImage' : ActorMethod<[number], undefined>,
  'removeStaff' : ActorMethod<[number], undefined>,
  'removeStudent' : ActorMethod<[number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitApplication' : ActorMethod<[AdmissionApplication], number>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];