/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FeesStructure = IDL.Record({
  'id' : IDL.Nat16,
  'period' : IDL.Text,
  'messFeesPerMonth' : IDL.Nat,
  'notes' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat16,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'uploadedAt' : Time,
  'uploadedBy' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Nat16,
  'bio' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat16,
  'admissionDate' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Text,
  'fatherName' : IDL.Text,
  'rollNumber' : IDL.Text,
  'category' : IDL.Text,
  'classLevel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AdmissionApplication = IDL.Record({
  'id' : IDL.Nat16,
  'institutionAddress' : IDL.Opt(IDL.Text),
  'status' : ApplicationStatus,
  'residenceCertUrl' : IDL.Opt(IDL.Text),
  'localGuardianName' : IDL.Opt(IDL.Text),
  'applicantName' : IDL.Text,
  'photoIdentityType' : IDL.Opt(IDL.Text),
  'institutionName' : IDL.Text,
  'graduationCertUrl' : IDL.Opt(IDL.Text),
  'healthProblems' : IDL.Opt(IDL.Text),
  'class10CertUrl' : IDL.Opt(IDL.Text),
  'guardianContact' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Text,
  'mentionCommunity' : IDL.Opt(IDL.Text),
  'annualIncome' : IDL.Text,
  'identificationMark' : IDL.Opt(IDL.Text),
  'submittedAt' : Time,
  'localGuardianMobile' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Text,
  'reviewNote' : IDL.Text,
  'guardianRelationship' : IDL.Opt(IDL.Text),
  'applicantMobile' : IDL.Text,
  'reviewedAt' : IDL.Opt(Time),
  'district' : IDL.Text,
  'courseDuration' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
  'fatherName' : IDL.Text,
  'bloodGroup' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'class12CertUrl' : IDL.Opt(IDL.Text),
  'incomeCertUrl' : IDL.Text,
  'category' : IDL.Text,
  'pinCode' : IDL.Text,
  'academicRowsJson' : IDL.Opt(IDL.Text),
  'courseName' : IDL.Opt(IDL.Text),
  'guardianName' : IDL.Opt(IDL.Text),
  'classYear' : IDL.Text,
  'currentYearSemester' : IDL.Opt(IDL.Text),
  'presentAddress' : IDL.Opt(IDL.Text),
  'guardianOccupation' : IDL.Opt(IDL.Text),
  'photoIdentityNo' : IDL.Opt(IDL.Text),
  'casteCertUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettings = IDL.Record({
  'announcementText' : IDL.Text,
  'admissionLink' : IDL.Text,
  'studentsEnrolled' : IDL.Text,
  'scholarshipLink' : IDL.Text,
  'scholarshipsFacilitated' : IDL.Text,
  'seatsAvailable' : IDL.Text,
  'yearsOfService' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateFees' : IDL.Func([FeesStructure], [], []),
  'addOrUpdateGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addOrUpdateStaff' : IDL.Func([StaffMember], [], []),
  'addOrUpdateStudent' : IDL.Func([Student], [], []),
  'approveApplication' : IDL.Func([IDL.Nat16, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAddStudents' : IDL.Func([IDL.Vec(Student)], [], []),
  'deleteAllStudents' : IDL.Func([], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(AdmissionApplication)],
      ['query'],
    ),
  'getAllFees' : IDL.Func([], [IDL.Vec(FeesStructure)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFees' : IDL.Func([IDL.Nat16], [FeesStructure], ['query']),
  'getGalleryImage' : IDL.Func([IDL.Nat16], [GalleryImage], ['query']),
  'getMyApplication' : IDL.Func([IDL.Text], [AdmissionApplication], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getStaffMember' : IDL.Func([IDL.Nat16], [StaffMember], ['query']),
  'getStudent' : IDL.Func([IDL.Nat16], [Student], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginApplicant' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerApplicant' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectApplication' : IDL.Func([IDL.Nat16, IDL.Text], [], []),
  'removeFees' : IDL.Func([IDL.Nat16], [], []),
  'removeGalleryImage' : IDL.Func([IDL.Nat16], [], []),
  'removeStaff' : IDL.Func([IDL.Nat16], [], []),
  'removeStudent' : IDL.Func([IDL.Nat16], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func([AdmissionApplication], [IDL.Nat16], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FeesStructure = IDL.Record({
    'id' : IDL.Nat16,
    'period' : IDL.Text,
    'messFeesPerMonth' : IDL.Nat,
    'notes' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat16,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Nat16,
    'bio' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat16,
    'admissionDate' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Text,
    'fatherName' : IDL.Text,
    'rollNumber' : IDL.Text,
    'category' : IDL.Text,
    'classLevel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AdmissionApplication = IDL.Record({
    'id' : IDL.Nat16,
    'institutionAddress' : IDL.Opt(IDL.Text),
    'status' : ApplicationStatus,
    'residenceCertUrl' : IDL.Opt(IDL.Text),
    'localGuardianName' : IDL.Opt(IDL.Text),
    'applicantName' : IDL.Text,
    'photoIdentityType' : IDL.Opt(IDL.Text),
    'institutionName' : IDL.Text,
    'graduationCertUrl' : IDL.Opt(IDL.Text),
    'healthProblems' : IDL.Opt(IDL.Text),
    'class10CertUrl' : IDL.Opt(IDL.Text),
    'guardianContact' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Text,
    'mentionCommunity' : IDL.Opt(IDL.Text),
    'annualIncome' : IDL.Text,
    'identificationMark' : IDL.Opt(IDL.Text),
    'submittedAt' : Time,
    'localGuardianMobile' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Text,
    'reviewNote' : IDL.Text,
    'guardianRelationship' : IDL.Opt(IDL.Text),
    'applicantMobile' : IDL.Text,
    'reviewedAt' : IDL.Opt(Time),
    'district' : IDL.Text,
    'courseDuration' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
    'fatherName' : IDL.Text,
    'bloodGroup' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'class12CertUrl' : IDL.Opt(IDL.Text),
    'incomeCertUrl' : IDL.Text,
    'category' : IDL.Text,
    'pinCode' : IDL.Text,
    'academicRowsJson' : IDL.Opt(IDL.Text),
    'courseName' : IDL.Opt(IDL.Text),
    'guardianName' : IDL.Opt(IDL.Text),
    'classYear' : IDL.Text,
    'currentYearSemester' : IDL.Opt(IDL.Text),
    'presentAddress' : IDL.Opt(IDL.Text),
    'guardianOccupation' : IDL.Opt(IDL.Text),
    'photoIdentityNo' : IDL.Opt(IDL.Text),
    'casteCertUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettings = IDL.Record({
    'announcementText' : IDL.Text,
    'admissionLink' : IDL.Text,
    'studentsEnrolled' : IDL.Text,
    'scholarshipLink' : IDL.Text,
    'scholarshipsFacilitated' : IDL.Text,
    'seatsAvailable' : IDL.Text,
    'yearsOfService' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateFees' : IDL.Func([FeesStructure], [], []),
    'addOrUpdateGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addOrUpdateStaff' : IDL.Func([StaffMember], [], []),
    'addOrUpdateStudent' : IDL.Func([Student], [], []),
    'approveApplication' : IDL.Func([IDL.Nat16, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAddStudents' : IDL.Func([IDL.Vec(Student)], [], []),
    'deleteAllStudents' : IDL.Func([], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(AdmissionApplication)],
        ['query'],
      ),
    'getAllFees' : IDL.Func([], [IDL.Vec(FeesStructure)], ['query']),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFees' : IDL.Func([IDL.Nat16], [FeesStructure], ['query']),
    'getGalleryImage' : IDL.Func([IDL.Nat16], [GalleryImage], ['query']),
    'getMyApplication' : IDL.Func(
        [IDL.Text],
        [AdmissionApplication],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getStaffMember' : IDL.Func([IDL.Nat16], [StaffMember], ['query']),
    'getStudent' : IDL.Func([IDL.Nat16], [Student], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginApplicant' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerApplicant' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectApplication' : IDL.Func([IDL.Nat16, IDL.Text], [], []),
    'removeFees' : IDL.Func([IDL.Nat16], [], []),
    'removeGalleryImage' : IDL.Func([IDL.Nat16], [], []),
    'removeStaff' : IDL.Func([IDL.Nat16], [], []),
    'removeStudent' : IDL.Func([IDL.Nat16], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func([AdmissionApplication], [IDL.Nat16], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };