/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface StaffMember {
    id: number;
    bio: string;
    order: bigint;
    name: string;
    designation: string;
    role: string;
    photoUrl: string;
    email: string;
    phone: string;
}
export interface SiteSettings {
    announcementText: string;
    admissionLink: string;
    studentsEnrolled: string;
    scholarshipLink: string;
    scholarshipsFacilitated: string;
    seatsAvailable: string;
    yearsOfService: string;
}
export type Time = bigint;
export interface GalleryImage {
    id: number;
    title: string;
    imageUrl: string;
    uploadedAt: Time;
    uploadedBy: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FeesStructure {
    id: number;
    period: string;
    messFeesPerMonth: bigint;
    notes: string;
    category: string;
}
export interface AdmissionApplication {
    id: number;
    institutionAddress?: string;
    status: ApplicationStatus;
    residenceCertUrl?: string;
    localGuardianName?: string;
    applicantName: string;
    photoIdentityType?: string;
    institutionName: string;
    graduationCertUrl?: string;
    healthProblems?: string;
    class10CertUrl?: string;
    guardianContact?: string;
    dateOfBirth: string;
    mentionCommunity?: string;
    annualIncome: string;
    identificationMark?: string;
    submittedAt: Time;
    localGuardianMobile?: string;
    photoUrl: string;
    reviewNote: string;
    guardianRelationship?: string;
    applicantMobile: string;
    reviewedAt?: Time;
    district: string;
    courseDuration?: string;
    state: string;
    fatherName: string;
    bloodGroup?: string;
    address: string;
    class12CertUrl?: string;
    incomeCertUrl: string;
    category: string;
    pinCode: string;
    academicRowsJson?: string;
    courseName?: string;
    guardianName?: string;
    classYear: string;
    currentYearSemester?: string;
    presentAddress?: string;
    guardianOccupation?: string;
    photoIdentityNo?: string;
    casteCertUrl: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface Student {
    id: number;
    admissionDate: string;
    name: string;
    year: string;
    fatherName: string;
    rollNumber: string;
    category: string;
    classLevel: string;
}
export enum ApplicationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateFees(feesStructure: FeesStructure): Promise<void>;
    addOrUpdateGalleryImage(image: GalleryImage): Promise<void>;
    addOrUpdateStaff(staffMember: StaffMember): Promise<void>;
    addOrUpdateStudent(student: Student): Promise<void>;
    approveApplication(id: number, note: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkAddStudents(newStudents: Array<Student>): Promise<void>;
    deleteAllStudents(): Promise<void>;
    getAllApplications(): Promise<Array<AdmissionApplication>>;
    getAllFees(): Promise<Array<FeesStructure>>;
    getAllGalleryImages(): Promise<Array<GalleryImage>>;
    getAllStaff(): Promise<Array<StaffMember>>;
    getAllStudents(): Promise<Array<Student>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFees(id: number): Promise<FeesStructure>;
    getGalleryImage(id: number): Promise<GalleryImage>;
    getMyApplication(mobile: string): Promise<AdmissionApplication>;
    getSiteSettings(): Promise<SiteSettings>;
    getStaffMember(id: number): Promise<StaffMember>;
    getStudent(id: number): Promise<Student>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginApplicant(mobile: string, pin: string): Promise<void>;
    registerApplicant(mobile: string, pin: string, name: string): Promise<void>;
    rejectApplication(id: number, note: string): Promise<void>;
    removeFees(id: number): Promise<void>;
    removeGalleryImage(id: number): Promise<void>;
    removeStaff(id: number): Promise<void>;
    removeStudent(id: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitApplication(applicationRequest: AdmissionApplication): Promise<number>;
    updateSiteSettings(newSettings: SiteSettings): Promise<void>;
}
import type { AdmissionApplication as _AdmissionApplication, ApplicationStatus as _ApplicationStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateFees(arg0: FeesStructure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateFees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateFees(arg0);
            return result;
        }
    }
    async addOrUpdateGalleryImage(arg0: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateGalleryImage(arg0);
            return result;
        }
    }
    async addOrUpdateStaff(arg0: StaffMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateStaff(arg0);
            return result;
        }
    }
    async addOrUpdateStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateStudent(arg0);
            return result;
        }
    }
    async approveApplication(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAddStudents(arg0: Array<Student>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddStudents(arg0);
            return result;
        }
    }
    async deleteAllStudents(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllStudents();
            return result;
        }
    }
    async getAllApplications(): Promise<Array<AdmissionApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFees(): Promise<Array<FeesStructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFees();
            return result;
        }
    }
    async getAllGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryImages();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<StaffMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFees(arg0: number): Promise<FeesStructure> {
        if (this.processError) {
            try {
                const result = await this.actor.getFees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFees(arg0);
            return result;
        }
    }
    async getGalleryImage(arg0: number): Promise<GalleryImage> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImage(arg0);
            return result;
        }
    }
    async getMyApplication(arg0: string): Promise<AdmissionApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplication(arg0);
                return from_candid_AdmissionApplication_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplication(arg0);
            return from_candid_AdmissionApplication_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async getStaffMember(arg0: number): Promise<StaffMember> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffMember(arg0);
            return result;
        }
    }
    async getStudent(arg0: number): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginApplicant(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.loginApplicant(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginApplicant(arg0, arg1);
            return result;
        }
    }
    async registerApplicant(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerApplicant(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerApplicant(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectApplication(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplication(arg0, arg1);
            return result;
        }
    }
    async removeFees(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFees(arg0);
            return result;
        }
    }
    async removeGalleryImage(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGalleryImage(arg0);
            return result;
        }
    }
    async removeStaff(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStaff(arg0);
            return result;
        }
    }
    async removeStudent(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStudent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitApplication(arg0: AdmissionApplication): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(to_candid_AdmissionApplication_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(to_candid_AdmissionApplication_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSiteSettings(arg0: SiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return result;
        }
    }
}
function from_candid_AdmissionApplication_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionApplication): AdmissionApplication {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    institutionAddress: [] | [string];
    status: _ApplicationStatus;
    residenceCertUrl: [] | [string];
    localGuardianName: [] | [string];
    applicantName: string;
    photoIdentityType: [] | [string];
    institutionName: string;
    graduationCertUrl: [] | [string];
    healthProblems: [] | [string];
    class10CertUrl: [] | [string];
    guardianContact: [] | [string];
    dateOfBirth: string;
    mentionCommunity: [] | [string];
    annualIncome: string;
    identificationMark: [] | [string];
    submittedAt: _Time;
    localGuardianMobile: [] | [string];
    photoUrl: string;
    reviewNote: string;
    guardianRelationship: [] | [string];
    applicantMobile: string;
    reviewedAt: [] | [_Time];
    district: string;
    courseDuration: [] | [string];
    state: string;
    fatherName: string;
    bloodGroup: [] | [string];
    address: string;
    class12CertUrl: [] | [string];
    incomeCertUrl: string;
    category: string;
    pinCode: string;
    academicRowsJson: [] | [string];
    courseName: [] | [string];
    guardianName: [] | [string];
    classYear: string;
    currentYearSemester: [] | [string];
    presentAddress: [] | [string];
    guardianOccupation: [] | [string];
    photoIdentityNo: [] | [string];
    casteCertUrl: string;
}): {
    id: number;
    institutionAddress?: string;
    status: ApplicationStatus;
    residenceCertUrl?: string;
    localGuardianName?: string;
    applicantName: string;
    photoIdentityType?: string;
    institutionName: string;
    graduationCertUrl?: string;
    healthProblems?: string;
    class10CertUrl?: string;
    guardianContact?: string;
    dateOfBirth: string;
    mentionCommunity?: string;
    annualIncome: string;
    identificationMark?: string;
    submittedAt: Time;
    localGuardianMobile?: string;
    photoUrl: string;
    reviewNote: string;
    guardianRelationship?: string;
    applicantMobile: string;
    reviewedAt?: Time;
    district: string;
    courseDuration?: string;
    state: string;
    fatherName: string;
    bloodGroup?: string;
    address: string;
    class12CertUrl?: string;
    incomeCertUrl: string;
    category: string;
    pinCode: string;
    academicRowsJson?: string;
    courseName?: string;
    guardianName?: string;
    classYear: string;
    currentYearSemester?: string;
    presentAddress?: string;
    guardianOccupation?: string;
    photoIdentityNo?: string;
    casteCertUrl: string;
} {
    return {
        id: value.id,
        institutionAddress: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.institutionAddress)),
        status: from_candid_ApplicationStatus_n14(_uploadFile, _downloadFile, value.status),
        residenceCertUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.residenceCertUrl)),
        localGuardianName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.localGuardianName)),
        applicantName: value.applicantName,
        photoIdentityType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.photoIdentityType)),
        institutionName: value.institutionName,
        graduationCertUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.graduationCertUrl)),
        healthProblems: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.healthProblems)),
        class10CertUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.class10CertUrl)),
        guardianContact: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.guardianContact)),
        dateOfBirth: value.dateOfBirth,
        mentionCommunity: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mentionCommunity)),
        annualIncome: value.annualIncome,
        identificationMark: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.identificationMark)),
        submittedAt: value.submittedAt,
        localGuardianMobile: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.localGuardianMobile)),
        photoUrl: value.photoUrl,
        reviewNote: value.reviewNote,
        guardianRelationship: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.guardianRelationship)),
        applicantMobile: value.applicantMobile,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.reviewedAt)),
        district: value.district,
        courseDuration: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.courseDuration)),
        state: value.state,
        fatherName: value.fatherName,
        bloodGroup: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.bloodGroup)),
        address: value.address,
        class12CertUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.class12CertUrl)),
        incomeCertUrl: value.incomeCertUrl,
        category: value.category,
        pinCode: value.pinCode,
        academicRowsJson: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.academicRowsJson)),
        courseName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.courseName)),
        guardianName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.guardianName)),
        classYear: value.classYear,
        currentYearSemester: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.currentYearSemester)),
        presentAddress: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.presentAddress)),
        guardianOccupation: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.guardianOccupation)),
        photoIdentityNo: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.photoIdentityNo)),
        casteCertUrl: value.casteCertUrl
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdmissionApplication>): Array<AdmissionApplication> {
    return value.map((x)=>from_candid_AdmissionApplication_n11(_uploadFile, _downloadFile, x));
}
function to_candid_AdmissionApplication_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdmissionApplication): _AdmissionApplication {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    institutionAddress?: string;
    status: ApplicationStatus;
    residenceCertUrl?: string;
    localGuardianName?: string;
    applicantName: string;
    photoIdentityType?: string;
    institutionName: string;
    graduationCertUrl?: string;
    healthProblems?: string;
    class10CertUrl?: string;
    guardianContact?: string;
    dateOfBirth: string;
    mentionCommunity?: string;
    annualIncome: string;
    identificationMark?: string;
    submittedAt: Time;
    localGuardianMobile?: string;
    photoUrl: string;
    reviewNote: string;
    guardianRelationship?: string;
    applicantMobile: string;
    reviewedAt?: Time;
    district: string;
    courseDuration?: string;
    state: string;
    fatherName: string;
    bloodGroup?: string;
    address: string;
    class12CertUrl?: string;
    incomeCertUrl: string;
    category: string;
    pinCode: string;
    academicRowsJson?: string;
    courseName?: string;
    guardianName?: string;
    classYear: string;
    currentYearSemester?: string;
    presentAddress?: string;
    guardianOccupation?: string;
    photoIdentityNo?: string;
    casteCertUrl: string;
}): {
    id: number;
    institutionAddress: [] | [string];
    status: _ApplicationStatus;
    residenceCertUrl: [] | [string];
    localGuardianName: [] | [string];
    applicantName: string;
    photoIdentityType: [] | [string];
    institutionName: string;
    graduationCertUrl: [] | [string];
    healthProblems: [] | [string];
    class10CertUrl: [] | [string];
    guardianContact: [] | [string];
    dateOfBirth: string;
    mentionCommunity: [] | [string];
    annualIncome: string;
    identificationMark: [] | [string];
    submittedAt: _Time;
    localGuardianMobile: [] | [string];
    photoUrl: string;
    reviewNote: string;
    guardianRelationship: [] | [string];
    applicantMobile: string;
    reviewedAt: [] | [_Time];
    district: string;
    courseDuration: [] | [string];
    state: string;
    fatherName: string;
    bloodGroup: [] | [string];
    address: string;
    class12CertUrl: [] | [string];
    incomeCertUrl: string;
    category: string;
    pinCode: string;
    academicRowsJson: [] | [string];
    courseName: [] | [string];
    guardianName: [] | [string];
    classYear: string;
    currentYearSemester: [] | [string];
    presentAddress: [] | [string];
    guardianOccupation: [] | [string];
    photoIdentityNo: [] | [string];
    casteCertUrl: string;
} {
    return {
        id: value.id,
        institutionAddress: value.institutionAddress ? candid_some(value.institutionAddress) : candid_none(),
        status: to_candid_ApplicationStatus_n22(_uploadFile, _downloadFile, value.status),
        residenceCertUrl: value.residenceCertUrl ? candid_some(value.residenceCertUrl) : candid_none(),
        localGuardianName: value.localGuardianName ? candid_some(value.localGuardianName) : candid_none(),
        applicantName: value.applicantName,
        photoIdentityType: value.photoIdentityType ? candid_some(value.photoIdentityType) : candid_none(),
        institutionName: value.institutionName,
        graduationCertUrl: value.graduationCertUrl ? candid_some(value.graduationCertUrl) : candid_none(),
        healthProblems: value.healthProblems ? candid_some(value.healthProblems) : candid_none(),
        class10CertUrl: value.class10CertUrl ? candid_some(value.class10CertUrl) : candid_none(),
        guardianContact: value.guardianContact ? candid_some(value.guardianContact) : candid_none(),
        dateOfBirth: value.dateOfBirth,
        mentionCommunity: value.mentionCommunity ? candid_some(value.mentionCommunity) : candid_none(),
        annualIncome: value.annualIncome,
        identificationMark: value.identificationMark ? candid_some(value.identificationMark) : candid_none(),
        submittedAt: value.submittedAt,
        localGuardianMobile: value.localGuardianMobile ? candid_some(value.localGuardianMobile) : candid_none(),
        photoUrl: value.photoUrl,
        reviewNote: value.reviewNote,
        guardianRelationship: value.guardianRelationship ? candid_some(value.guardianRelationship) : candid_none(),
        applicantMobile: value.applicantMobile,
        reviewedAt: value.reviewedAt ? candid_some(value.reviewedAt) : candid_none(),
        district: value.district,
        courseDuration: value.courseDuration ? candid_some(value.courseDuration) : candid_none(),
        state: value.state,
        fatherName: value.fatherName,
        bloodGroup: value.bloodGroup ? candid_some(value.bloodGroup) : candid_none(),
        address: value.address,
        class12CertUrl: value.class12CertUrl ? candid_some(value.class12CertUrl) : candid_none(),
        incomeCertUrl: value.incomeCertUrl,
        category: value.category,
        pinCode: value.pinCode,
        academicRowsJson: value.academicRowsJson ? candid_some(value.academicRowsJson) : candid_none(),
        courseName: value.courseName ? candid_some(value.courseName) : candid_none(),
        guardianName: value.guardianName ? candid_some(value.guardianName) : candid_none(),
        classYear: value.classYear,
        currentYearSemester: value.currentYearSemester ? candid_some(value.currentYearSemester) : candid_none(),
        presentAddress: value.presentAddress ? candid_some(value.presentAddress) : candid_none(),
        guardianOccupation: value.guardianOccupation ? candid_some(value.guardianOccupation) : candid_none(),
        photoIdentityNo: value.photoIdentityNo ? candid_some(value.photoIdentityNo) : candid_none(),
        casteCertUrl: value.casteCertUrl
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApplicationStatus.pending ? {
        pending: null
    } : value == ApplicationStatus.approved ? {
        approved: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
